management:
  endpoints:
    web:
      base-path: /private
      exposure:
        include: prometheus
        exclude: metrics
      path-mapping:
        prometheus: metrics

server:
  servlet:
    context-path: /application_name
  tomcat:
    accept-count: 120
    mbeanregistry:
      enabled: true
    threads:
      max: 1200

spring:
  datasource:
    url: 'jdbc:h2:mem:resource1'
    driverClassName: 'org.h2.Driver'
    username: 'dbuser'
    password: 'dbpass'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        web-allow-others: true
