server:
  tomcat:
    threads:
      max: 400

spring:
  sql:
    init:
      mode: 'embedded'
      schema-locations: 'classpath:schema-local.sql'
      data-locations: 'classpath:truncate-table-local.sql, classpath:data-local.sql'
  jpa:
    hibernate:
      ddl-auto: 'none'
